namespace Darwin.Contracts.Common;

/// <summary>
/// RFC 7807-like problem details payload used for error responses
/// on the public Web API.
/// </summary>
public sealed class ProblemDetails
{
    /// <summary>
    /// Gets or sets a machine-readable error type URI.
    /// For example: \"https://docs.darwincms.com/errors/validation\".
    /// </summary>
    public string? Type { get; set; }

    /// <summary>
    /// Gets or sets a short, human-readable summary of the problem.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the HTTP status code generated by the server.
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// Gets or sets a human-readable explanation specific to this occurrence.
    /// </summary>
    public string? Detail { get; set; }

    /// <summary>
    /// Gets or sets the request URI that generated the problem.
    /// </summary>
    public string? Instance { get; set; }

    /// <summary>
    /// Gets or sets a bag of additional key/value pairs providing
    /// structured details. Commonly used for validation errors.
    /// </summary>
    public Dictionary<string, string[]> Extensions { get; set; } = new();
}
