namespace Darwin.Contracts.Common;

/// <summary>
/// Minimal RFC 7807 problem details contract for consistent error responses.
/// </summary>
public sealed class ProblemDetails
{
    /// <summary>A URI reference that identifies the problem type.</summary>
    public string? Type { get; init; }

    /// <summary>A short, human-readable summary of the problem type.</summary>
    public string? Title { get; init; }

    /// <summary>HTTP status code generated by the origin server for this occurrence.</summary>
    public int? Status { get; init; }

    /// <summary>A human-readable explanation specific to this occurrence of the problem.</summary>
    public string? Detail { get; init; }

    /// <summary>A URI reference that identifies the specific occurrence of the problem.</summary>
    public string? Instance { get; init; }
}
